### ISSUE TITLE
I meet a problem when i run "./notionterm"

### ISSUE THREAD

**Issue by golowper** [ariary/notionterm#13]
os : ubuntu:20.04
this is specific info
>root@docker-desktop:/home/notionterm# ./notionterm
./notionterm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./notionterm)

**Comment by ariary** [comment]
Did you use the release version?

**Comment by golowper** [comment]
Yes and i want to build it by myself. How can I do it?

**Comment by ariary** [comment]
Yes I suggest you to build it on your own
You need golang (and eventually make)
Clone the repo then:
```shell
make before.build
make build.notionterm
```

if you wait a bit I will publish a release more stable and easy to use (~1 week)

**Comment by golowper** [comment]
Thanks , I rebuild it and then it works !
